services:
  - type: web
    name: django-blog
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn blog.wsgi
    disk:
      name: media
      mountPath: /opt/render/project/media
      sizeGB: 1